on:
  push:
    branches:
    - master
  
jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
    - name: render
      run: |
        .github/render_readme.rb > README.md
        
    - name: Commit files
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add README.md
        git commit -m "[auto] update README.md"
        git push origin master
